server:
  port: 19095 # Auth 서비스 포트 번호

spring:
  application:
    name: auth-service # 애플리케이션 이름

  datasource:
    url: jdbc:postgresql://postgres:5432/${DB_NAME} # postgreSql URL
    username: ${DB_USER} # 데이터베이스 사용자명
    password: ${DB_PW} # 데이터베이스 비밀번호
    driver-class-name: org.postgresql.Driver # postgreSql 드라이버
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect # PostgreSQL에 맞는 Dialect
    hibernate:
      ddl-auto: none
    show-sql: true

#  data:
#    redis:
#      host: localhost
#      port: 6379
#      username: default
#      password: systempass

eureka:
  client:
    service-url:
      defaultZone: http://eureka:19090/eureka/ # Eureka URL

service:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    # JWT 비밀키

    access-expiration: 3600000 # JWT 만료 시간 (ms)

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "*"

  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0
