version: '3.8'

services:
  redis-stack:
    image: redis/redis-stack
    container_name: caching_redis
    restart: always
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "6380:6379"
      - "8002:8001"
    networks:
      - tms-network

  zipkin:
    image: openzipkin/zipkin:3.4.2
    container_name: zipkin
    ports:
      - "9411:9411"
    restart: unless-stopped
    networks:
      - tms-network

networks:
  tms-network:
    driver: bridge
