SPRING_DATASOURCE_URL : jdbc:postgresql://postgres:5432/${DB_NAME}
SPRING_DATASOURCE_USERNAME : ${DB_USER}
SPRING_DATASOURCE_PASSWORD : ${DB_PW}
REDIS_HOST : redis
REDIS_PORT : 6380
REDIS_USERNAME : default
REDIS_PASSWORD : ${REDIS_PW}
EUREKA_NAME : eureka
EUREKA_HOST : eureka
EUREKA_PORT : 19090